uwsgi:
  wsgi-file: ./app.py
  socket: 127.0.0.1:3032
  daemonize: logs/a.log
  plugins: python
  workers: 4
  stats: 127.0.0.1:1717
  pidfile: /tmp/project-master.pid
  cheaper: 4
  idle: 6000
  master: true
